example(points)
x <- rnorm(100)
y <- rnorm(100)
plot(x,y, pch=20)
title("Scatterplot")
text(-2,-2, "***")
legend("topleft", legend = "data")
legend("topleft", legend = "data", pch = 20)
fit <- lm(y~x)
abline(fit)
abline(fit, lwd=3)
abline(fit, lwd=3, col="blue")
plot(x, y, xlab="Weight", ylab = "Height", main="Scatterplot", pch = 20)
legend("topright", legend= "Data", pch= 20)
fit <- lm(y~x)
abline(fit, lwd=3, col="blue")
##arrange 2 plots under each other
z <- rpois(100, 2)
par(mfrow = c(2,1))
plot(x, y, xlab="Weight", ylab = "Height", main="Scatterplot", pch = 20)
legend("topright", legend= "Data", pch= 20)
plot(x,z, pch = 19)
par("mar")
par(mar = c(2,2,1,1))
par(mfrow = c(2,1))
plot(x, y, xlab="Weight", ylab = "Height", main="Scatterplot", pch = 20)
legend("topright", legend= "Data", pch= 20)
plot(x,z, pch = 19)
##arrange 2 plots next to each other
par(mar = c(4,2,2,2))
par(mfrow = c(1,2))
plot(x, y, xlab="Weight", ylab = "Height", main="Scatterplot", pch = 20)
legend("topright", legend= "Data", pch= 20)
plot(x,z, pch = 19)
##arrange 4 plots next to each other
par(mar = c(4,2,2,2))
par(mfrow = c(2,2))
plot(x, y, xlab="Weight", ylab = "Height", main="Scatterplot", pch = 20)
legend("topright", legend= "Data", pch= 20)
plot(x,z, pch = 19)
plot(y,z, pch = 20)
plot(y,x, pch = 16)
##mfcol changes the order how plots appear
##plotting 2 groups of variables
par(mfrow=c(1,1))
x <- rnorm(100)
y <- x+rnorm(100)
g <- gl(2,50)
g <- gl(2,50, labels = c("Male", "Female"), pch=20)
str(g)
plot(x,y, type = "n") ##set up an empty plot
points(x[g== "Male"], y[g=="Male"], col = "green") ##plot the males first
points(x[g== "Female"], y[g=="Female"], col = "blue", pch = 19) ##plot the males first

